CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(300)		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(100)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지 요청 경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(FK)';

CREATE TABLE "AUTH_KEY" (
	"KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	VARCHAR2(10)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."KEY_NO" IS '인증키 구분 번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증 번호';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

CREATE TABLE "COMMENT_REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_REASON"	NVARCHAR2(100)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"PROCESS_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "COMMENT_REPORT"."REPORT_NO" IS '댓글 신고 번호(PK)';

COMMENT ON COLUMN "COMMENT_REPORT"."REPORT_REASON" IS '댓글 신고 사유';

COMMENT ON COLUMN "COMMENT_REPORT"."REPORT_DATE" IS '댓글 신고 날짜';

COMMENT ON COLUMN "COMMENT_REPORT"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "COMMENT_REPORT"."COMMENT_NO" IS '댓글 번호(PK)';

COMMENT ON COLUMN "COMMENT_REPORT"."PROCESS_YN" IS '신고 처리 여부';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호(PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(FK)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모 댓글 번호(FK)';

CREATE TABLE "SCRAP" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SCRAP"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "SCRAP"."MEMBER_NO" IS '회원번호(PK)';

CREATE TABLE "BOARD_LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원번호(PK)';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(20)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_RRN"	VARCHAR2(500)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_PW"	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원ID';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_RRN" IS '회원 주민등록번호';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 유형';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

CREATE TABLE "UPLOAD_FILE" (
	"FILE_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"FILE_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"FILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"FILE_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_NO" IS '파일 번호(PK)';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_PATH" IS '파일 경로';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_ORIGINAL_NAME" IS '파일 원본명';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_RENAME" IS '파일 변경명';

COMMENT ON COLUMN "UPLOAD_FILE"."FILE_UPLOAD_DATE" IS '업로드 날짜';

COMMENT ON COLUMN "UPLOAD_FILE"."MEMBER_NO" IS '회원번호(FK)';

CREATE TABLE "INFO_SCRAP" (
	"INFO_BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "INFO_SCRAP"."INFO_BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "INFO_SCRAP"."MEMBER_NO" IS '회원번호(PK)';

CREATE TABLE "INFO_BOARD" (
	"INFO_BOARD_NO"	NUMBER		NOT NULL,
	"SCH_SIDO"	VARCHAR2(100)		NOT NULL,
	"SCH_SIGN"	VARCHAR2(100)		NOT NULL,
	"PROGRM_BGNDE"	VARCHAR2(50)		NOT NULL,
	"PROGRM_ENDDE"	VARCHAR2(50)		NOT NULL,
	"ADULT_POSBL_AT"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"YNG_BGS_POSBL_AT"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ACT_BEGIN_TM"	NUMBER		NOT NULL,
	"ACT_END_TM"	NUMBER		NOT NULL,
	"NOTICE_BGN_DE"	VARCHAR2(30)		NOT NULL,
	"NOTICE_END_DE"	VARCHAR2(30)		NOT NULL,
	"ACT_PLACE"	VARCHAR2(50)		NOT NULL,
	"NANMM_BY_NM"	VARCHAR2(200)		NOT NULL,
	"URL"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "INFO_BOARD"."INFO_BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "INFO_BOARD"."SCH_SIDO" IS '지역코드 - 시/도';

COMMENT ON COLUMN "INFO_BOARD"."SCH_SIGN" IS '지역코드 - 구/군';

COMMENT ON COLUMN "INFO_BOARD"."PROGRM_BGNDE" IS '봉사시작일자';

COMMENT ON COLUMN "INFO_BOARD"."PROGRM_ENDDE" IS '봉사종료일자';

COMMENT ON COLUMN "INFO_BOARD"."ADULT_POSBL_AT" IS '성인가능여부';

COMMENT ON COLUMN "INFO_BOARD"."YNG_BGS_POSBL_AT" IS '청소년가능여부';

COMMENT ON COLUMN "INFO_BOARD"."ACT_BEGIN_TM" IS '봉사시작시간';

COMMENT ON COLUMN "INFO_BOARD"."ACT_END_TM" IS '봉사종료시간';

COMMENT ON COLUMN "INFO_BOARD"."NOTICE_BGN_DE" IS '모집시작일';

COMMENT ON COLUMN "INFO_BOARD"."NOTICE_END_DE" IS '모집종료일';

COMMENT ON COLUMN "INFO_BOARD"."ACT_PLACE" IS '봉사장소';

COMMENT ON COLUMN "INFO_BOARD"."NANMM_BY_NM" IS '모집기관';

COMMENT ON COLUMN "INFO_BOARD"."URL" IS '사이트';

CREATE TABLE "BOARD_REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"REPORT_REASON"	NVARCHAR2(100)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROCESS_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPORT"."REPORT_NO" IS '신고 번호(PK)';

COMMENT ON COLUMN "BOARD_REPORT"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_NO" IS '게시글 번호(FK)';

COMMENT ON COLUMN "BOARD_REPORT"."REPORT_REASON" IS '신고 사유(욕설/도배 등)';

COMMENT ON COLUMN "BOARD_REPORT"."REPORT_DATE" IS '신고 날짜';

COMMENT ON COLUMN "BOARD_REPORT"."PROCESS_YN" IS '관리자 처리 여부';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 종류 코드 번호(PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 명';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_PW"	NVARCHAR2(100)		NOT NULL,
	"BOARD_LOCK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."BOARD_PW" IS '게시글 비밀번호';

COMMENT ON COLUMN "BOARD"."BOARD_LOCK" IS '비밀글 여부';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 종류 코드 번호(FK)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호(FK)';

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"KEY_NO"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "PK_COMMENT_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "SCRAP" ADD CONSTRAINT "PK_SCRAP" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "UPLOAD_FILE" ADD CONSTRAINT "PK_UPLOAD_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "INFO_SCRAP" ADD CONSTRAINT "PK_INFO_SCRAP" PRIMARY KEY (
	"INFO_BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "INFO_BOARD" ADD CONSTRAINT "PK_INFO_BOARD" PRIMARY KEY (
	"INFO_BOARD_NO"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "PK_BOARD_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_REPORT_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_BOARD_TO_SCRAP_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_SCRAP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "UPLOAD_FILE" ADD CONSTRAINT "FK_MEMBER_TO_UPLOAD_FILE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "INFO_SCRAP" ADD CONSTRAINT "FK_INFO_BOARD_TO_INFO_SCRAP_1" FOREIGN KEY (
	"INFO_BOARD_NO"
)
REFERENCES "INFO_BOARD" (
	"INFO_BOARD_NO"
);

ALTER TABLE "INFO_SCRAP" ADD CONSTRAINT "FK_MEMBER_TO_INFO_SCRAP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_BOARD_TO_BOARD_REPORT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

-- 1. 멤버 테이블 중복 방지 (필수)
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_ID" UNIQUE ("MEMBER_ID");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_NICKNAME" UNIQUE ("MEMBER_NICKNAME");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_EMAIL" UNIQUE ("MEMBER_EMAIL");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_RRN" UNIQUE ("MEMBER_RRN");
ALTER TABLE "MEMBER" ADD CONSTRAINT "UK_MEMBER_TEL" UNIQUE ("MEMBER_TEL");

-- 2. 게시판 이름 중복 방지
ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "UK_BOARD_NAME" UNIQUE ("BOARD_NAME");

-- 3. 중복 신고 방지 (필수)
ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "UK_BOARD_REPORT" UNIQUE ("MEMBER_NO", "BOARD_NO");
ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "UK_COMMENT_REPORT" UNIQUE ("MEMBER_NO", "COMMENT_NO");

-- 4. Y/N 값만 들어오게 강제 (체크 제약조건 - 권장)
ALTER TABLE "MEMBER" ADD CONSTRAINT "CHK_MEMBER_DEL_FL" CHECK ("MEMBER_DEL_FL" IN ('Y', 'N'));
ALTER TABLE "BOARD" ADD CONSTRAINT "CHK_BOARD_DEL_FL" CHECK ("BOARD_DEL_FL" IN ('Y', 'N'));
ALTER TABLE "BOARD" ADD CONSTRAINT "CHK_BOARD_LOCK" CHECK ("BOARD_LOCK" IN ('Y', 'N'));
ALTER TABLE "COMMENT" ADD CONSTRAINT "CHK_COMMENT_DEL_FL" CHECK ("COMMENT_DEL_FL" IN ('Y', 'N'));

/* ------------------------------------------------------ */
/* 시퀀스 일괄 생성 (9개)                  */
/* ------------------------------------------------------ */

-- 1. 회원 번호 (MEMBER 테이블)
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 2. 게시글 번호 (BOARD 테이블)
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

-- 3. 댓글 번호 (COMMENT 테이블)
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

-- 4. 게시판 이미지 번호 (BOARD_IMG 테이블)
CREATE SEQUENCE SEQ_IMG_NO NOCACHE;

-- 5. 파일 업로드 번호 (UPLOAD_FILE 테이블)
CREATE SEQUENCE SEQ_FILE_NO NOCACHE;

-- 6. 이메일 인증키 번호 (AUTH_KEY 테이블)
CREATE SEQUENCE SEQ_KEY_NO NOCACHE;

-- 7. 게시글 신고 번호 (BOARD_REPORT 테이블)
CREATE SEQUENCE SEQ_REPORT_NO NOCACHE;

-- 8. 댓글 신고 번호 (COMMENT_REPORT 테이블) - ★ 방금 추가한 거
CREATE SEQUENCE SEQ_COMMENT_REPORT_NO NOCACHE;

-- 9. 정보 게시판 게시글 번호(INFO_BOARD 테이블)
CREATE SEQUENCE SEQ_INFO_BOARD_NO NOCACHE;

-- (선택) 게시판 종류 코드 (BOARD_TYPE 테이블)
CREATE SEQUENCE SEQ_BOARD_CODE NOCACHE;

/* ------------------------------------------------------ */
/* 시퀀스가 필요 없는 테이블들 (참고)             */
/* ------------------------------------------------------ */
/*
 1. INFO_BOARD : BOARD_NO를 PK이자 FK로 씀 (1:1 관계) -> SEQ_BOARD_NO 공유
 2. SCRAP      : (MEMBER_NO + BOARD_NO) 복합키 사용 -> 시퀀스 X
 3. BOARD_LIKE : (MEMBER_NO + BOARD_NO) 복합키 사용 -> 시퀀스 X
*/

COMMIT;